name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Train Model
      run: python model.py

    - name: Run Tests
      run: python -m pytest test.py

    - name: Build Docker Image
      run: docker build -t ml-model .

    - name: Run Docker Container (Test Deploy)
      run: docker run ml-model